### PR TITLE
Created module Secure-ChainKit v2

### PR DESCRIPTION
**Pull request by lucdekens**
- converted the Secure-ChainKit.ps1 to a module
  - added a module manifest
- renamed the functions to use approved verbs
- converted functions to use standard parameter definitions
- changed user/password to a PSCredential (otherwise module will not pass PSScriptAnalyzer)
- used a module variable ($script:ChainKitToken) to store token. This to avoid having to pass user/password or having to store those in environment variables
- added script Check-Module-v2.ps1 to demonstrate module
- added sample-1.ps1 for demo, it uses a PowerCLI cmdlet
- some minor changes to be conform with current PowerShell coding style

Signed-off-by: Luc Dekens <dekens.luc@gmail.com>

### CODE REVIEW

**Comment by lucdekens** [comment]
Removed clear text credentials

**Comment by lucdekens** [comment]
Demo 2 added

**Comment by lucdekens** [comment]
Demo 3, audit script, added

**Review by guilt — APPROVED** [review]
Great! Thank you, @lucdekens ... This is some fantastic stuff :)

**Pull request merged**
